name = "webhook-replay-studio-api"
main = "src/index.ts"
compatibility_date = "2025-12-29"


[[d1_databases]]
binding = "DB"
database_name = "wrs_db"
database_id = "dab57f51-059a-4949-b9ee-26f8f8ed4abe"

[vars]
PUBLIC_API_BASE = "http://127.0.0.1:8787"
APP_ORIGIN = "http://localhost:5173"
